import { NextRequest, NextResponse } from "next/server";
import Razorpay from "razorpay";
import { prisma } from "@/lib/prisma";
import { razorpay } from "@/lib/razorpay";
import { Prisma } from "@/generated/prisma/client";
import { processPaymentEvent } from "@/services/process-payment-event";

// The events this endpoint currently acts on. Subscription lifecycle events
// (subscription.charged/pending/halted/...) are intentionally out of scope
// for now — this phase only turns payment.* events into Payment rows.
const HANDLED_EVENTS = new Set(["payment.captured", "payment.failed"]);

// The response to Razorpay itself returns in well under this — the extra
// headroom is for the deferred after() callback (the Gemini explanation
// call), which runs after that response is already sent.
export const maxDuration = 30;

interface RazorpayPaymentEntity {
  id: string;
  amount: number;
  currency: string;
  order_id: string | null;
  invoice_id: string | null;
  error_code: string | null;
  error_description: string | null;
  error_reason: string | null;
}

interface RazorpayWebhookPayload {
  event: string;
  payload: {
    payment?: { entity: RazorpayPaymentEntity };
  };
}

export async function POST(request: NextRequest) {
  const secret = process.env.RAZORPAY_WEBHOOK_SECRET;
  if (!secret) {
    console.error("RAZORPAY_WEBHOOK_SECRET is not set");
    return NextResponse.json({ error: "Webhook not configured" }, { status: 500 });
  }

  // Signature is HMAC-SHA256 over the raw, unparsed body — must be read as
  // text before any JSON parsing, or verification will fail.
  const rawBody = await request.text();
  const signature = request.headers.get("x-razorpay-signature");
  // Unique per delivery; only in this header, never in the JSON body itself.
  const eventId = request.headers.get("x-razorpay-event-id");

  if (!signature || !eventId) {
    return NextResponse.json({ error: "Missing signature or event id header" }, { status: 400 });
  }

  let signatureValid: boolean;
  try {
    signatureValid = Razorpay.validateWebhookSignature(rawBody, signature, secret);
  } catch {
    signatureValid = false;
  }
  if (!signatureValid) {
    return NextResponse.json({ error: "Invalid signature" }, { status: 400 });
  }

  let payload: RazorpayWebhookPayload;
  try {
    payload = JSON.parse(rawBody);
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  // Razorpay retries non-2xx/timed-out deliveries for up to 24h, so the same
  // event id can arrive more than once. Let the unique constraint on
  // razorpayEventId be the source of truth for "already seen" under races.
  let webhookEvent;
  try {
    webhookEvent = await prisma.webhookEvent.create({
      data: { razorpayEventId: eventId, eventType: payload.event, payload: payload as unknown as Prisma.InputJsonValue },
    });
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      return NextResponse.json({ status: "already processed" }, { status: 200 });
    }
    throw error;
  }

  try {
    if (HANDLED_EVENTS.has(payload.event)) {
      await handlePaymentEvent(payload);
    }
    await prisma.webhookEvent.update({
      where: { id: webhookEvent.id },
      data: { processedAt: new Date() },
    });
  } catch (error) {
    await prisma.apiError.create({
      data: {
        source: "webhook:razorpay",
        context: payload.event,
        message: error instanceof Error ? error.message : "Unknown error",
        details: { eventId },
      },
    });
    // Still ack with 200: the event is durably recorded in WebhookEvent
    // (processedAt stays null) and in ApiError. Returning non-2xx would only
    // make Razorpay retry an event we've already logged.
  }

  return NextResponse.json({ status: "ok" }, { status: 200 });
}

async function handlePaymentEvent(payload: RazorpayWebhookPayload) {
  const payment = payload.payload.payment?.entity;
  if (!payment) return;

  // Subscription-cycle payments carry invoice_id, not order_id (order_id is
  // for order/checkout-initiated payments) — there is no subscription_id
  // field on the payment entity itself. Resolve the local Subscription via
  // the Razorpay Invoice's subscription_id, the same lookup Razorpay's own
  // WooCommerce subscriptions plugin uses for this exact correlation.
  if (!payment.invoice_id) return;

  const invoice = await razorpay.invoices.fetch(payment.invoice_id);
  // The razorpay npm package's types omit subscription_id from the invoice
  // response entity (it only appears on the .all() query-filter type), but
  // Razorpay does populate it on invoices generated by a subscription cycle
  // — confirmed against razorpay/razorpay-woocommerce-subscriptions, which
  // reads this exact field for this exact correlation.
  const razorpaySubscriptionId = (invoice as unknown as { subscription_id?: string })
    .subscription_id;
  if (!razorpaySubscriptionId) return;

  const subscription = await prisma.subscription.findUnique({
    where: { razorpaySubscriptionId },
  });
  if (!subscription) return;

  await processPaymentEvent({
    subscriptionId: subscription.id,
    eventType: payload.event === "payment.captured" ? "payment.captured" : "payment.failed",
    razorpayPaymentId: payment.id,
    razorpayOrderId: payment.order_id,
    amount: payment.amount,
    currency: payment.currency,
    errorCode: payment.error_code,
    errorDescription: payment.error_description,
    errorReason: payment.error_reason,
  });
}
